### ISSUE TITLE
ActivityMainBinding

### ISSUE THREAD

**Issue by alexiusacademia** [ajaysaini-sgvu/root-persistence-sample#2]
Hi there. I was wondering where is the code for com.nagarro.persistence.databinding.ActivityMainBinding? Thank you!

**Comment by ajaysaini-sgvu** [comment]
Hi @alexiusacademia  

The Data Binding Library generates binding classes that are used to access the layout's variables and views. This https://developer.android.com/topic/libraries/data-binding/generated-binding  page shows how to create and customize generated binding classes.
